<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>User List Report</title>
    <style>
        @font-face {
            font-family: 'siemreap-regular';
            src: url('{{ public_path('fonts/Siemreap-Regular.ttf') }}');
        }
        .siemreap-regular {
            font-family: "siemreap-regular", sans-serif;
            font-weight: 400;
            font-style: normal;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 15px;
        }

        .header h1 {
            margin: 0;
            font-size: 24px;
            color: #333;
            font-weight: bold;
        }

        .header p {
            margin: 5px 0 0 0;
            font-size: 14px;
            color: #666;
        }

        .info-section {
            margin-bottom: 20px;
            display: table;
            width: 100%;
        }

        .info-left {
            display: table-cell;
            width: 50%;
        }

        .info-right {
            display: table-cell;
            width: 50%;
            text-align: right;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            font-size: 11px;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f8f9fa;
            font-weight: bold;
            text-align: center;
            color: #333;
        }

        tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        tr:hover {
            background-color: #f5f5f5;
        }

        .text-center {
            text-align: center;
        }

        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 15px;
        }

        .total-count {
            font-weight: bold;
            color: #333;
            margin: 10px 0;
        }

        .badge {
            background-color: #e3f2fd;
            color: #1976d2;
            padding: 2px 8px;
            border-radius: 12px;
            font-size: 10px;
            font-weight: bold;
        }

        .badge-admin {
            background-color: #fff3e0;
            color: #f57c00;
        }

        .no-data {
            text-align: center;
            padding: 40px;
            color: #666;
            font-style: italic;
        }
    </style>
</head>
<body>
    <!-- Header Section -->
    <div class="header">
        <h2>User List Report</h2>
    </div>

    <!-- Info Section -->
    <div class="info-section">
        <div class="info-left siemreap-regular">
            <strong>Print Date:</strong> {{ date('F j, Y g:i A') }}
        </div>
        <div class="info-right siemreap-regular">
            <strong>Total Users:</strong> {{ $users->count() }} users
        </div>
    </div>

    <div class="total-count siemreap-regular">
        Total: {{ $users->count() }} users
    </div>

    @if($users->count() > 0)
        <!-- Users Table -->
        <table>
            <thead>
                <tr>
                    <th class="siemreap-regular" style="width: 8%;">No.</th>
                    <th class="siemreap-regular" style="width: 12%;">User ID</th>
                    <th class="siemreap-regular" style="width: 25%;">Full Name</th>
                    <th class="siemreap-regular" style="width: 25%;">Email</th>
                    <th class="siemreap-regular" style="width: 15%;">Phone</th>
                    <th class="siemreap-regular" style="width: 15%;">Role</th>
                </tr>
            </thead>
            <tbody>
                @foreach($users as $index => $user)
                    <tr>
                        <td class="text-center siemreap-regular">{{ $index + 1 }}</td>
                        <td class="text-center siemreap-regular">{{ $user->user_id ?? 'N/A' }}</td>
                        <td class="siemreap-regular">{{ $user->full_name }}</td>
                        <td class="siemreap-regular">{{ $user->email }}</td>
                        <td class="text-center siemreap-regular">{{ $user->phone }}</td>
                        <td class="text-center siemreap-regular">
                            <span class="badge {{ $user->role === 'admin' ? 'badge-admin' : '' }}">
                                {{ ucfirst($user->role) }}
                            </span>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div class="no-data siemreap-regular">
            <p>No user data available</p>
        </div>
    @endif

    <!-- Footer Section -->
    <div class="footer">
        <p class="siemreap-regular">Generated by: User Management TOKTOK System</p>
        <p>{{ config('app.name') }} - {{ date('Y') }}</p>
    </div>
</body>
</html>
